apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: default
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
    - targetPort: 5672
      port: 5672
  selector:
    app: rabbitmq
